# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../test_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'TEST' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  install_all_flutter_pods(flutter_application_path)

  # Pods for TEST

  target 'TESTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TESTUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
